# # import win32gui
# # import win32con
# #
# # def upload(filePath, browser_type="chrome"):
# #     '''
# #     通过pywin32模块实现文件上传的操作
# #     :param filePath: 文件的绝对路径
# #     :param browser_type: 浏览器类型（默认值为chrome）
# #     :return:
# #     '''
# #     if browser_type.lower() == "chrome":
# #         title = "打开"
# #     elif browser_type.lower() == "firefox":
# #         title = "文件上传"
# #     elif browser_type.lower() == "ie":
# #         title = "选择要加载的文件"
# #     else:
# #         title = ""  # 这里根据其它不同浏览器类型来修改
# #
# #     # 找元素
# #     # 一级窗口"#32770","打开"
# #     dialog = win32gui.FindWindow("#32770", title)
# #     # 向下传递
# #     ComboBoxEx32 = win32gui.FindWindowEx(dialog, 0, "ComboBoxEx32", None)  # 二级
# #     comboBox = win32gui.FindWindowEx(ComboBoxEx32, 0, "ComboBox", None)   # 三级
# #     # 编辑按钮
# #     edit = win32gui.FindWindowEx(comboBox, 0, 'Edit', None)  # 四级
# #     # 打开按钮
# #     button = win32gui.FindWindowEx(dialog, 0, 'Button', "打开(&O)")  # 二级
# #
# #     # 输入文件的绝对路径，点击“打开”按钮
# #     win32gui.SendMessage(edit, win32con.WM_SETTEXT, None, filePath)  # 发送文件路径
# #     win32gui.SendMessage(dialog, win32con.WM_COMMAND, 1, button)  # 点击打开按钮
# # if __name__=='__main__':
# #     filePath='C:\\Users\\h\\Pictures\\模板\\000013.png'
# #     upload(filePath)
# #从selenium里面导入webdriver
# from selenium import webdriver
# import  time
# 
# #指定chrom的驱动
# #执行到这里的时候Selenium会到指定的路径将chrome driver程序运行起来
# driver = webdriver.Chrome()
# #driver = webdriver.Firefox()#这里是火狐的浏览器运行方法
# 
# #get 方法 打开指定网址
# driver.get('http://kb-apps.yunxiao.com/login')
# time.sleep(3)
# 
# #选择网页元素
# driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[2]/div/form/div[1]/div/div/input').send_keys(18239902182)
# driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[2]/div/form/div[2]/div/div/input').send_keys("123456.")
# driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[2]/div/form/div[3]/div/button[1]').click()
# time.sleep(3)
# driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div[2]/div/div/div/span').click()
# time.sleep(10)
# driver.find_element_by_xpath('//*[@id="app"]/div/div[2]/div/div[3]/div[3]/div[1]/div[1]/div[1]/div[5]/div/div/label[1]/span[1]').click()
# 
# 
# #输入字符
# # element_keyword.send_keys('宋曲')
# 
# #找到搜索按钮
# element_search_button = driver.find_element_by_id('su')
[{'script_id': 219, 'script_testDataName': '用户登录', 'script_testDataPositioning': '', 'script_testDataKeyWord': 'openbrowser', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': 'http://kb-apps.yunxiao.com/login chrome', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '69', 'script_testResult': ''},
 {'script_id': 220, 'script_testDataName': 'KBP-输入账号', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'sendKeys', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div/div[2]/div[2]/div/form/div[1]/div/div/input', 'script_testDataParameter': '18239902182', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '69', 'script_testResult': ''},
 {'script_id': 221, 'script_testDataName': 'KBP-输入密码', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'sendKeys', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div/div[2]/div[2]/div/form/div[2]/div/div/input', 'script_testDataParameter': '123456.', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '69', 'script_testResult': ''},
 {'script_id': 222, 'script_testDataName': 'KBP-点击登录', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div/div[2]/div[2]/div/form/div[3]/div/button[1]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '69', 'script_testResult': ''},
 {'script_id': 224, 'script_testDataName': 'KBP-点击内容管理', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div/div/div[2]/div/div/div/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '69', 'script_testResult': ''},
 {'script_id': 229, 'script_testDataName': '切换窗口', 'script_testDataPositioning': '', 'script_testDataKeyWord': 'changeHandle', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '72', 'script_testResult': ''},
 {'script_id': 230, 'script_testDataName': '选择人教A版', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/div[1]/div[2]/div/div/label[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '72', 'script_testResult': ''},
 {'script_id': 231, 'script_testDataName': '断言-集合与常用逻辑用语', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[3]/div[1]/div[1]/div[4]/div[1]/div[1]/span[2]/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '72', 'script_testResult': '成功'},
 {'script_id': 232, 'script_testDataName': '类型选择-知识树', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/div[1]/div[1]/div/div/label[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '73', 'script_testResult': ''},
 {'script_id': 233, 'script_testDataName': '断言-类型选择-知识树', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/div[1]/div[2]/div/div/label[1]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '73', 'script_testResult': '成功'},
 {'script_id': 234, 'script_testDataName': '类型选择-知识树', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/div[1]/div/div/div/label[3]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '74', 'script_testResult': ''},
 {'script_id': 235, 'script_testDataName': '类型选择-知识树', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[3]/div[1]/div[1]/div[4]/div[1]/div[1]/span[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '74', 'script_testResult': '成功'},
 {'script_id': 236, 'script_testDataName': '类型选择-教材', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/div[1]/div/div/div/label[1]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '75', 'script_testResult': ''},
 {'script_id': 237, 'script_testDataName': '类型选择-版本-人教B版', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/div[1]/div[2]/div/div/label[3]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '75', 'script_testResult': ''},
 {'script_id': 238, 'script_testDataName': '类型选择-版本-人教B版', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[3]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div/span[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '75', 'script_testResult': '成功'},
 {'script_id': 239, 'script_testDataName': '类型选择-教材', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/div[1]/div[3]/div/div/label[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '76', 'script_testResult': ''},
 {'script_id': 241, 'script_testDataName': '类型选择-版本-人教B版', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[3]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div/span[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '76', 'script_testResult': '成功'},
 {'script_id': 242, 'script_testDataName': '关键字搜索', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'sendKeys', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div/input', 'script_testDataParameter': '读下列程序，写出此程序表示的函数，并求当输出的y=9时，输入的x的值', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '77', 'script_testResult': ''},
 {'script_id': 243, 'script_testDataName': '关键字搜索-开始搜索', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div/div[2]/button', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '77', 'script_testResult': ''},
 {'script_id': 244, 'script_testDataName': '断言-关键字搜索', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[3]/div[1]/div[1]/div[1]/p', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '77', 'script_testResult': '成功'},
 {'script_id': 245, 'script_testDataName': '点击-关键字搜索tab', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div/div[1]/div/div/input', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '78', 'script_testResult': ''},
 {'script_id': 251, 'script_testDataName': '点击-选择ID搜索', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '/html/body/div[6]/div[1]/div[1]/ul/li[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '78', 'script_testResult': ''},
 {'script_id': 252, 'script_testDataName': '清空查询条件', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clearElementValue', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div/input', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '78', 'script_testResult': ''},
 {'script_id': 253, 'script_testDataName': '点击-输入ID查询', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'sendKeys', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div/input', 'script_testDataParameter': '4028125124', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '78', 'script_testResult': ''},
 {'script_id': 254, 'script_testDataName': '点击查询', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div/div[2]/button', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '78', 'script_testResult': ''},
 {'script_id': 255, 'script_testDataName': 'ID查询-断言', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[3]/div/div/div[2]/div[2]/div[1]', 'script_testDataParameter': '试题ID：4028125124', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '78', 'script_testResult': '成功'},
 {'script_id': 271, 'script_testDataName': '强制等待4', 'script_testDataPositioning': '', 'script_testDataKeyWord': 'forcedWaitTime', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '4', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '81', 'script_testResult': ''},
 {'script_id': 272, 'script_testDataName': '点击查看相似题', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[3]/div/div/div[2]/div[2]/div[3]/div[1]/button/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '81', 'script_testResult': ''},
 {'script_id': 273, 'script_testDataName': '点击查看', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[3]/div/div/div[2]/div[2]/div[3]/div[2]/button/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '82', 'script_testResult': ''},
 {'script_id': 274, 'script_testDataName': '断言-点击查看', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '/html/body/div[8]/div/div[1]/span', 'script_testDataParameter': '试题详情', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '82', 'script_testResult': '成功'},
 {'script_id': 275, 'script_testDataName': '关闭弹窗', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '/html/body/div[8]/div/div[1]/button/i', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '82', 'script_testResult': ''},
 {'script_id': 276, 'script_testDataName': '点击返回题库', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div[1]/button/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '84', 'script_testResult': ''},
 {'script_id': 277, 'script_testDataName': '断言-返回题库', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/span', 'script_testDataParameter': '搜索试题：', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '84', 'script_testResult': '成功'},
 {'script_id': 278, 'script_testDataName': '进入试题纠错', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[1]/ul/li[1]/ul/li[2]/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '85', 'script_testResult': ''},
 {'script_id': 279, 'script_testDataName': '断言-进入试题纠错', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="tab-first"]', 'script_testDataParameter': '待修正列表', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '85', 'script_testResult': '成功'},
 {'script_id': 280, 'script_testDataName': '进入试题纠错', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="pane-first"]/div/div[1]/div/div/input', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '86', 'script_testResult': ''},
 {'script_id': 281, 'script_testDataName': '进入试题纠错-选择错误类型为题干错误', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '/html/body/div[5]/div[1]/div[1]/ul/li[3]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '86', 'script_testResult': ''},
 {'script_id': 282, 'script_testDataName': '断言-选择错误类型为题干错误', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="pane-first"]/div/div[2]/div[1]/div[1]/div[3]/div/div[1]/div[1]/div/span[1]/span', 'script_testDataParameter': '题干有误', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '86', 'script_testResult': '成功'},
 {'script_id': 283, 'script_testDataName': '选择已修正列表', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="tab-second"]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '87', 'script_testResult': ''},
 {'script_id': 284, 'script_testDataName': '断言-选择已修正列表', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="tab-first"]', 'script_testDataParameter': '待修正列表', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '87', 'script_testResult': '成功'},
 {'script_id': 285, 'script_testDataName': '点击报错有效性', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="pane-second"]/div/div[1]/div[2]/div/input', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '88', 'script_testResult': ''},
 {'script_id': 286, 'script_testDataName': '选择报错无效', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '/html/body/div[6]/div[1]/div[1]/ul/li[3]/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '88', 'script_testResult': ''},
 {'script_id': 287, 'script_testDataName': '断言-选择报错无效', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="pane-second"]/div/div[2]/div[1]/div[1]/div[3]/div/div[1]/div[2]/div/button/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '88', 'script_testResult': '成功'},
 {'script_id': 288, 'script_testDataName': '点击试题入库审查', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[1]/ul/li[1]/ul/li[3]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '90', 'script_testResult': ''},
 {'script_id': 289, 'script_testDataName': '断言-试题入库审查', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="pane-first"]/div[1]/label[1]/span', 'script_testDataParameter': '优先审查', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '90', 'script_testResult': '成功'},
 {'script_id': 290, 'script_testDataName': '入库审查-点击全部试题', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="pane-first"]/div[1]/label[2]/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '91', 'script_testResult': ''},
 {'script_id': 291, 'script_testDataName': '断言-入库审查-点击全部试题', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="pane-first"]/div[1]/label[2]/span', 'script_testDataParameter': '全部试题', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '91', 'script_testResult': '成功'},
 {'script_id': 292, 'script_testDataName': '入库审查-点击全部试题', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="tab-second"]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '92', 'script_testResult': ''},
 {'script_id': 293, 'script_testDataName': '入库审查-点击全部试题', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="tab-second"]', 'script_testDataParameter': '已抛弃', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '92', 'script_testResult': '成功'},
 {'script_id': 294, 'script_testDataName': '点击试卷管理', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[1]/ul/li[2]/div', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '93', 'script_testResult': ''},
 {'script_id': 295, 'script_testDataName': '点击常规试卷', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[1]/ul/li[2]/ul/li[1]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '93', 'script_testResult': ''},
 {'script_id': 296, 'script_testDataName': '断言-常规试卷', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/span', 'script_testDataParameter': '搜索试卷：', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '93', 'script_testResult': '成功'},
 {'script_id': 297, 'script_testDataName': '常规试卷-关键字搜索', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'sendKeys', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div/div[2]/input', 'script_testDataParameter': '2018年11月浙江省普通高校招生选考生物试卷', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '94', 'script_testResult': ''},
 {'script_id': 298, 'script_testDataName': '常规试卷-关键字搜索-点击搜索', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div/button', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '94', 'script_testResult': ''},
 {'script_id': 304, 'script_testDataName': '断言-常规试卷-关键字搜索-点击搜索', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/ul/li[1]/span[1]/a/span[1]', 'script_testDataParameter': '2018年', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '94', 'script_testResult': '成功'},
 {'script_id': 299, 'script_testDataName': '常规试卷-ID搜索-点击请选择', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div/div[1]/div/input', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '95', 'script_testResult': ''},
 {'script_id': 300, 'script_testDataName': '常规试卷-选择ID搜索', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '/html/body/div[5]/div[1]/div[1]/ul/li[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '95', 'script_testResult': ''},
 {'script_id': 301, 'script_testDataName': '常规试卷-选择ID搜索-清空搜索框', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clearElementValue', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div/div[2]/input', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '95', 'script_testResult': ''},
 {'script_id': 302, 'script_testDataName': '常规试卷-选择ID搜索-输入ID3131896831', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'sendKeys', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div/div[2]/input', 'script_testDataParameter': '3131896831', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '95', 'script_testResult': ''},
 {'script_id': 303, 'script_testDataName': '常规试卷-选择ID搜索-输入ID3131896831-点击搜索', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div/div/button', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '95', 'script_testResult': ''},
 {'script_id': 305, 'script_testDataName': '断言-常规试卷-选择ID搜索-输入ID3131896831', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/ul/li/span[1]/span/span[2]', 'script_testDataParameter': '试卷ID：3131896831', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '95', 'script_testResult': '成功'},
 {'script_id': 306, 'script_testDataName': '常规试卷-ID搜索-点击试卷分析', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/ul/li/span[2]/button[1]/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '96', 'script_testResult': ''},
 {'script_id': 307, 'script_testDataName': '切换窗口索-点击试卷分析-返回主窗口', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'changeNewHandele', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '96', 'script_testResult': ''},
 {'script_id': 308, 'script_testDataName': '断言-常规试卷-ID搜索-点击试卷分析', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div/div/div[1]/span[2]/span[1]', 'script_testDataParameter': '试卷分析', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '96', 'script_testResult': '成功'},
 {'script_id': 309, 'script_testDataName': '等待3s切换窗口', 'script_testDataPositioning': '', 'script_testDataKeyWord': 'closeHandle', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '96', 'script_testResult': ''},
 {'script_id': 316, 'script_testDataName': '等待3s切换窗口', 'script_testDataPositioning': '', 'script_testDataKeyWord': 'changeNewHandele', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '96', 'script_testResult': ''},
 {'script_id': 311, 'script_testDataName': '常规试卷-ID搜索-点击查看', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/ul/li/span[2]/button[2]/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '98', 'script_testResult': ''},
 {'script_id': 313, 'script_testDataName': '常规试卷-ID搜索-点击查看', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'changeNewHandele', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '98', 'script_testResult': ''},
 {'script_id': 314, 'script_testDataName': '断言-常规试卷-ID搜索-点击查看', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="paper"]/div[1]/div/div/span[2]/span[1]', 'script_testDataParameter': '试卷预览', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '98', 'script_testResult': '成功'},
 {'script_id': 315, 'script_testDataName': '常规试卷-ID搜索-点击查看-关闭窗口', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'closeHandle', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '98', 'script_testResult': ''},
 {'script_id': 322, 'script_testDataName': '常规试卷-ID搜索-点击查看-关闭窗口', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'changeNewHandele', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '98', 'script_testResult': ''},
 {'script_id': 317, 'script_testDataName': '返回常规试卷', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'getRectUrl', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': 'http://kbp.yunxiao.com/manage/exampapers/exampaper', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '99', 'script_testResult': ''},
 {'script_id': 318, 'script_testDataName': '常规试卷-选择沪科版', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/div[1]/div[2]/span[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '99', 'script_testResult': ''},
 {'script_id': 319, 'script_testDataName': '常规试卷-选择高一', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/div[2]/div[2]/span[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '99', 'script_testResult': ''},
 {'script_id': 320, 'script_testDataName': '常规试卷-选择高考模拟', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/div[3]/div[2]/span[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '99', 'script_testResult': ''},
 {'script_id': 321, 'script_testDataName': '断言-常规试卷-选择高考模拟', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[4]/ul/li/span[1]/span/span[2]', 'script_testDataParameter': '试卷ID：586742271', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '99', 'script_testResult': '成功'},
 {'script_id': 323, 'script_testDataName': '返回常规试卷', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'getRectUrl', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': 'http://kbp.yunxiao.com/manage/exampapers/exampaper', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '100', 'script_testResult': ''},
 {'script_id': 324, 'script_testDataName': '断言-返回常规试卷', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[1]/div[1]/div/div/label[2]/span/text()', 'script_testDataParameter': '单元测', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '100', 'script_testResult': ''},
 {'script_id': 325, 'script_testDataName': '点击试卷分析', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/ul/li[1]/span[2]/button[1]/span', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '101', 'script_testResult': ''},
 {'script_id': 326, 'script_testDataName': '点击试卷分析-切换窗口', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'changeNewHandele', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '101', 'script_testResult': ''},
 {'script_id': 327, 'script_testDataName': '断言-点击试卷分析', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div/div/div[1]/span[2]/span[1]\n', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '101', 'script_testResult': ''},
 {'script_id': 328, 'script_testDataName': '点击试卷分析-关闭窗口', 'script_testDataPositioning': '', 'script_testDataKeyWord': 'closeHandle', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '101', 'script_testResult': ''},
 {'script_id': 329, 'script_testDataName': '点击试卷分析-切换到最新窗口', 'script_testDataPositioning': '', 'script_testDataKeyWord': 'changeNewHandele', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '101', 'script_testResult': ''},
 {'script_id': 330, 'script_testDataName': '系列成品卷-点击试卷查看', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'clickElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="app"]/div/div[2]/div/div[2]/ul/li[1]/span[2]/button[2]', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '102', 'script_testResult': ''},
 {'script_id': 331, 'script_testDataName': '系列成品卷-点击试卷查看-切换到最新窗口', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'changeNewHandele', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '102', 'script_testResult': ''},
 {'script_id': 332, 'script_testDataName': '断言-系列成品卷-点击试卷查看', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'assertValueElement', 'script_testDataPremise': '', 'script_testDataElement': '//*[@id="paper"]/div[1]/div/div/span[2]/span[1]', 'script_testDataParameter': '试卷预览', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '102', 'script_testResult': ''},
 {'script_id': 333, 'script_testDataName': '系列成品卷-关闭弹窗', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'closeHandle', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '102', 'script_testResult': ''},
 {'script_id': 334, 'script_testDataName': '系列成品卷-切换到最新弹窗', 'script_testDataPositioning': 'Xpath', 'script_testDataKeyWord': 'changeNewHandele', 'script_testDataPremise': '', 'script_testDataElement': '', 'script_testDataParameter': '', 'script_testDataAssert': '', 'script_testDataProject': '74', 'script_testDataVersion': '21', 'script_TestDataCase': '102', 'script_testResult': ''}]